-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "email" character varying NOT NULL, "title" character varying NULL, PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create "blogs" table
CREATE TABLE "blogs" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "body" text NOT NULL, "created_at" timestamptz NOT NULL, "user_blog_posts" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "blogs_users_blog_posts" FOREIGN KEY ("user_blog_posts") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
